# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '15min_mokumoku' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 15min_mokumoku

  target '15min_mokumokuTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '15min_mokumokuUITests' do
    # Pods for testing
  end

end
